# Generated by Django 4.0.1 on 2022-03-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.CharField(max_length=200)),
                ('linea', models.CharField(max_length=200)),
                ('cantidad_en_stock', models.IntegerField(null=True)),
                ('precio_compra', models.IntegerField(default=0, null=True)),
                ('precio_venta', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('productos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventario.item', verbose_name='Orden')),
            ],
        ),
    ]
