# Generated by Django 4.0.1 on 2022-03-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
