# Generated by Django 4.0.1 on 2022-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='orden',
            name='cantidadvendida',
            field=models.IntegerField(null=True),
        ),
    ]
