# Generated by Django 4.0.1 on 2022-03-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_orden_subtotal_orden_cantidadvendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cantidadvendida',
            field=models.IntegerField(null=True, verbose_name='Cantidad Vendida'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='productos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventario.item', verbose_name='Producto'),
        ),
    ]
