# Generated by Django 4.0.1 on 2022-03-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_orden_cantidadvendida_alter_orden_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad Vendida')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('productos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventario.item', verbose_name='Producto')),
            ],
        ),
    ]
