# Generated by Django 4.0.1 on 2022-03-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_ingresopedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orden',
            new_name='OrdenDeVenta',
        ),
        migrations.AlterField(
            model_name='ingresopedido',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad a Ingresar'),
        ),
    ]
