# Generated by Django 4.0.1 on 2022-03-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='cantidad',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
