# Generated by Django 4.0.1 on 2022-03-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_ingresopedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeventa',
            name='cantidadvendida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Vendida'),
        ),
    ]
