# Generated by Django 4.0.1 on 2022-03-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_ordendeventa_cantidadvendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='subtotal',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
