# Generated by Django 4.0.1 on 2022-03-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_lista_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='productos',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventario.item', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
