# Generated by Django 4.0.1 on 2022-03-30 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_venta_alter_ordendeventa_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 30, 21, 3, 48, 956607, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
