# Generated by Django 4.0.1 on 2022-03-31 01:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_remove_venta_actualizado_remove_venta_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 31, 1, 41, 42, 998672, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresopedido',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad a Ingresar'),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='productos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventario.item', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
